#!/usr/bin/python
# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-
__author__ = "David Amian Valle <damian@emergya.com>"
__copyright__ = "Copyright (C) 2014, Junta de Andalucía <devmaster@guadalinex.org>"
__license__ = "GPL-2"

import os
import sys
import requests
import json
import subprocess
if __name__ == '__main__':
    fp = open('/tmp/ccwrapper-last.log', "w")
    args = sys.argv
    args.pop(0)
    try:
        gcc_flag = open ('/etc/gcc.control')
    except Exception as e:
        fp.write("This workstation is not linked")
        fp.close()
        sys.exit(1)
    content = gcc_flag.read()
    gcc_flag.close()
    gcc_flag_json = json.loads(content)
    url = gcc_flag_json['uri_gcc']
    node_id = gcc_flag_json['gcc_nodename']
    fp.write("Establecer socket con la api\n")
    try:
        res = requests.put(url+'/chef-client/run/', data={"node_id":node_id, "gcc_username":gcc_flag_json['gcc_username']})
    except Exception as e:
        fp.write("Error en la comunicación con GCC\n")
        fp.write(str(e))
        fp.close()
        sys.exit(1)
    if res.ok and res.json()['ok']:
        cmd = ['/usr/bin/chef-client']
        cmd = cmd + args
        process = subprocess.Popen(cmd)
        process.wait()
        fp.write(str(process.returncode) + '\n')
        if process.returncode != 0:
            fp.write("Comunicar el error a GCC\n")
            fp.close()
            sys.exit(1)
        else:
            fp.write("Todo OK\n")
            fp.close()
            sys.exit(0)
    else:
        fp.write("Comunicar el error a GCC\n")
        fp.close()
        sys.exit(1)